apply plugin: 'com.android.application'

android {
    namespace "com.airaware.app"

    compileSdkVersion 35

    defaultConfig {
        applicationId "com.airaware.app"
        minSdkVersion 24
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file("airaware-release.keystore")
            storePassword System.getenv("KEYSTORE_PASSWORD")
            keyAlias System.getenv("KEY_ALIAS")
            keyPassword System.getenv("KEY_PASSWORD")
        }
    }

    buildTypes {

        debug {
            minifyEnabled false
        }

        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            shrinkResources false
        }
    }
}

dependencies {
}
