name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Install Capacitor CLI
        run: npm install @capacitor/cli @capacitor/core @capacitor/android

      - name: Init Android
        run: npx cap add android || true

      - name: Sync
        run: npx cap sync android

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AirAware-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
